// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGJmSWm-nXxQ5qf4zAewoq07O1Ab35U0I',
    appId: '1:90110935970:web:47aa57667a8b960e4ba8fb',
    messagingSenderId: '90110935970',
    projectId: 'voting-app-d39ec',
    authDomain: 'voting-app-d39ec.firebaseapp.com',
    storageBucket: 'voting-app-d39ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJLhExZmveMWu8OCyHaNp1SXBOKYEarow',
    appId: '1:90110935970:android:699e3eb8a567163c4ba8fb',
    messagingSenderId: '90110935970',
    projectId: 'voting-app-d39ec',
    storageBucket: 'voting-app-d39ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQa6S5G33b0RCEaOMxpk9VtrjhUyRIuf4',
    appId: '1:90110935970:ios:a35a8773005f9a324ba8fb',
    messagingSenderId: '90110935970',
    projectId: 'voting-app-d39ec',
    storageBucket: 'voting-app-d39ec.appspot.com',
    iosBundleId: 'com.example.votingApp2',
  );

}